plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'vanessas_digital_portfolio'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

// Configuration for DevTools
configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    // Spring Boot Starters
    implementation 'org.springframework.boot:spring-boot-starter-web'       // MVC + REST
    implementation 'org.springframework.boot:spring-boot-starter-webflux'   // reactive / WebClient
    implementation 'org.springframework.boot:spring-boot-starter-graphql'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // DevTools for hot reload
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Annotation processor
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test' // includes JUnit Jupiter, Spring Test, MockMvc
    testImplementation 'org.junit.platform:junit-platform-launcher'          // ensures Gradle can run JUnit 5

}


// Use JUnit Platform for tests
tasks.named('test') {
    useJUnitPlatform()
}
