# Server Configuration
server.port=8080
spring.application.name=vanessas_digital_portfolio

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Static Resources
spring.web.resources.static-locations=classpath:/static/

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.example.vanessas_digital_portfolio=DEBUG